### ISSUE TITLE
No Inspecting object models on mac

### ISSUE THREAD

**Issue by AlexanderBoenninger** [seblavoie/sublime-extendscript#2]
Hey

The documentation says you will find the Inspecting object models, when you click on help 
https://extendscript.docsforadobe.dev/extendscript-toolkit/inspecting-object-models.html

On a Mac, there is no help button. How can I access the Inspecting object models?
It seems pretty essential.

Thanks for looking into it

**Comment by ff6347** [comment]
Your link about the Extendscript Toolkit (which is deprecated since a few years), has nothing to do with this Sublime Text extension. Also this extension has not been touched by the author since 9 years. I guess he moved on to do other things. Maybe you check https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug This is the current way do develop scripts for Adobe apps.

**Comment by seblavoie** [comment]
Thanks for answering @ff6347, I have indeed moved on to other things and I don't use this anymore. I would also suggest using the official Extendscript Debugger from Adobe.

**Comment by AlexanderBoenninger** [comment]
Thanks for answering, even though you moved on.
